### ISSUE TITLE
Crash on realloc

### ISSUE THREAD

**Issue by aganea** [microsoft/snmalloc#175] opened 2020-05-06 03:00 UTC
Hello, I'm seeing a 100% crash in snmalloc's realloc function, in malloc.cc, L92. The crash is caused by the `sz` being larger than the size initially allocated. We're trying to (re)allocate a large buffer:
```
llvm-mc.exe!realloc(void * ptr=0x0000023244000000, unsigned __int64 size=0x00000000027fffff)
```
In malloc.cc, L82, `Alloc::alloc_size(ptr);` finds `sz` to be `0x0000000002000000` bytes. However the caller knows the buffer is `0x013fffff`. So we end up crashing on `rep movsb` while copying the buffer to the new location.
I can see `alloc_size(..)` returning at alloc.h, L500, ie. `return 1ULL << size;` where size is 25.

I haven't investigated any further. I am at git checkout a43773c5b7e1fc291ddd1580fec04a574ef886e1. I'm trying to integrate snmalloc in LLVM to compare it with other modern allocators. Currently half a dozen tests are failing because of this. Any suggestions? I can provide with a repro if needed.

**Comment by SchrodingerZhu** [comment] 2020-05-06 05:18
```c++
#include <iostream>
int main() {
    int *a = static_cast<int *>(malloc(20'000'000 * sizeof(int)));
    a[10'000'000] = 123'000;
    a = static_cast<int *>(realloc(a, 40'000'000 * sizeof(int)));
    std::cout << a[10'000'000] << std::endl;
    free(a);
}
```

**Comment by mjp41** [comment] 2020-05-06 05:23
Is this with Debug or Release? Windows or Linux? I think I know what the problem is. For large allocations it has a power of two address range, but only the pages requested are actually enabled.

**Comment by mjp41** [comment] 2020-05-06 05:29
If you set "USE_POSIX_COMMIT_CHECKS" to "Off", does it still fail? E.g.

```
cmake -DUSE_POSIX_COMMIT_CHECKS=Off ..
```

**Comment by SchrodingerZhu** [comment] 2020-05-06 05:58
@mjp41 failed to reproduce on Linux. Windows 100% failure with SegFault with a block large enough.

**Comment by mjp41** [comment] 2020-05-06 06:26
I think the issue is

https://github.com/microsoft/snmalloc/blob/a43773c5b7e1fc291ddd1580fec04a574ef886e1/src/mem/largealloc.h#L369
and 
https://github.com/microsoft/snmalloc/blob/a43773c5b7e1fc291ddd1580fec04a574ef886e1/src/mem/largealloc.h#L392
are committing based on size. But the `alloc_size` call is returning based on `rsize`

The simplest fix is to use rsize, but this will commit more memory.

We could query with Virtual Query inside alloc_size to find the committed range. 

Or we could alter the page map to have more accurate size information for large allocs.

I think let's use rsize now, and a more complex fix with the page map later.

**Comment by mjp41** [comment] 2020-05-06 06:30
@aganea thanks for reporting, and sverry interested to find out how snmalloc performs. I saw you had been testing rpmalloc and mimalloc. Great to add snmalloc to the mix.

**Comment by SchrodingerZhu** [comment] 2020-05-06 06:35
I confirm the fix.

**Comment by aganea** [comment] 2020-05-06 13:01
Thanks for the quick fix!
I'm running on Windows indeed, on Release targets, on a two-stage build with Clang 10. 
I'll get back with results.

I ran into another issue, maybe you have an idea: I had to comment out `#define PLATFORM_HAS_VIRTUALALLOC2` in pal_windows.h, because `VirtualAlloc2FromApp` is always declared as dllimport. I'm building a /MT target (static, no DLLs). snmalloc is entirely compiled as part of LLVM. Not sure why `VirtualAlloc2FromApp` comes as decored with dllimport.

**Comment by aganea** [comment] 2020-05-06 22:06
The fix work, thanks again! All tests pass now in Clang, LLD, and LLVM (except for a DLL test which might exhibit issues mentionned here: https://twitter.com/maniccoder/status/1250768250503417857?s=20

Overall the performance of snmalloc seems equivalent to rpmalloc (using the https://github.com/mjansson/rpmalloc/tree/mjansson/llvm-opt branch) and to that of mimalloc. In terms of memory pages commited, mimalloc is well ahead, followed by rpmalloc, then snmalloc which has the highest commit usage. I can see in ETW profiles that generally snmalloc seems to commit less pages during the execution overall, but probably larger memory ranges.
I will do more tests and will post more detailed results on the LLVM review: https://reviews.llvm.org/D71786 (I will notify when that's updated)

**Closed** 2020-05-07 05:31 UTC

**Comment by mjp41** [comment] 2020-05-07 06:59
For your VirtualAlloc2 issue we have to link mincore.lib. I wonder if adding that would fix the dllimport issues.

**Comment by aganea** [comment] 2020-05-08 01:52
Hello again, please see below some tests I did linking **clang.exe** with a ThinLTO-built lld-link:
https://github.com/mjansson/rpmalloc/issues/150#issuecomment-625582836
snmalloc comes about on-par in terms of link time with rpmalloc and mimalloc, hower it has higher committed bytes. By the looks of it, it seems snmalloc allocates larger virtual memory ranges, and decommits a lot less often.

**Comment by mjp41** [comment] 2020-05-08 20:15
@aganea thanks for this, if you have any break down of where time is spent that would be super-useful. I have a few optimisation that would improve the windows perf, but I don't know if they would have sufficient effect without some profiling data.

**Comment by aganea** [comment] 2020-05-09 17:13
I do have profiles, although there's no obvious answer. All snmalloc calls are inlined, I don't see anything that stands out. Are there any statistics that I could enable in snmalloc?

**Comment by mjp41** [comment] 2020-05-09 17:55
Just high-level how long rpmalloc/snmalloc/mimalloc spend inside malloc and inside free, would be helpful.  I am guessing snmalloc is spending a lot longer on the fast path deallocation on Windows as the pagemap has not been optimised, and on other platforms we have a different implementation that takes advantage of lazy commit.
